"""- updated booking column with total

Revision ID: 838821a7bf7e
Revises: d283efd4b8d8
Create Date: 2025-11-02 15:30:36.206664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838821a7bf7e'
down_revision = 'd283efd4b8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
