"""Fixed the notification model

Revision ID: 8d4838e77a91
Revises: ef61cf8d00c4
Create Date: 2025-10-29 20:39:37.121542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d4838e77a91'
down_revision = 'ef61cf8d00c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('notifications_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['u_id'], ['u_id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_ibfk_1'), 'users', ['user_id'], ['u_id'], ondelete='CASCADE')
        batch_op.drop_column('u_id')

    # ### end Alembic commands ###
