"""Initial Migration

Revision ID: d283efd4b8d8
Revises: 
Create Date: 2025-10-30 00:32:55.106063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd283efd4b8d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transactions_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['booking_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transactions_ibfk_3'), 'bookings', ['booking_id'], ['booking_id'], ondelete='SET NULL')

    # ### end Alembic commands ###
