"""Initial Migration

Revision ID: ddd92a195a3c
Revises: 
Create Date: 2025-10-29 22:59:20.703221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddd92a195a3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=20), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
