"""Fixed the database models

Revision ID: ef61cf8d00c4
Revises: 5b42b0e27f1c
Create Date: 2025-10-29 20:01:14.129983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef61cf8d00c4'
down_revision = '5b42b0e27f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('notifications_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['u_id'], ondelete='CASCADE')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_ibfk_1'), 'users', ['customer_id'], ['u_id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
